**Q1**

An array is a collection of items stored at contiguous memory locations. The array contains multiple items of the same type together.

**Q2**

- **Array:**
    - Elements can't be of different data types: you can't combine strings, integers, and objects in the same array.
    - Arrays need to be declared.Creating an array, requires a specific function from either the array module (i.e., array.array()) or NumPy package (i.e., numpy.array()).
    - Arrays can store data very compactly and are more efficient for storing large amounts of data.
    - Arrays are great for numerical operations.For example, you can divide each element of an array by the same number with just one line of code.
    
- **List**
    - Elements can be of different data types: you can combine strings, integers, and objects in the same list.
    - list need to be declared, since they are built into Python.
    - List can't store data very compactly and are not efficient for storing large amounts of data.
    - List are not good for numerical operations.For example, you cannot divide each element of an list by the same number with just one line of code. If you try this with a list, you’ll get an error.
    

**Q3**

The shape of an array can be changed using **reshape()** function.

**Q4**

The name.strip() will returns a copy of the string(name) by removing both the leading and the trailing characters (based on the string argument passed).

example:

In [1]:
name='   patil    '
print(name.strip())
name1='www.patil.info'
print(name1.strip())

patil
www.patil.info


**Q5**

With triple quotes, we can print strings on multiple lines to make text, especially lengthy text, easier to read. 

**Q6**

In [2]:
import numpy as np

In [3]:
strarr=np.array('a b c d'.split())
strarr

array(['a', 'b', 'c', 'd'], dtype='<U1')

**Q7**

In [4]:
a='hello'
a[2:4]

'll'

**Q8**

In [5]:
arr1=np.array(range(1,11))
print(arr1.max())
print(arr1.min())

10
1


**Q9**

In [6]:
name='core python'
name2=name[5:]
print(name2)
name2[::-1]

python


'nohtyp'

**Q10**

In [7]:
arr2=np.array([5,10,15,20,25])
arr2

array([ 5, 10, 15, 20, 25])

In [8]:
np.append(arr2,12)

array([ 5, 10, 15, 20, 25, 12])

In [9]:
np.delete(arr2,2) #removes the element at 3rd positiom in an array

array([ 5, 10, 20, 25])

Alternative mathod: **(using remove())**

In [10]:
import array as arr
arr3=arr.array('i',range(5,16))
arr3.remove(5)
arr3

array('i', [6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

**Q11**

In [11]:
np.array(range(10,20)) #single dimensional array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
a=np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]],[[7,8,9],[7,8,9]]]) #3d array

**Q12**

In [13]:
str1='Programiz'
print(str1.upper())
print(str1.lower())
str1.replace(str1,'program')

PROGRAMIZ
programiz


'program'

**Q13**

In [14]:
arr3=np.linspace(10,15,10)
arr4=np.arange(10,20)
arr3+arr4

array([20.        , 21.55555556, 23.11111111, 24.66666667, 26.22222222,
       27.77777778, 29.33333333, 30.88888889, 32.44444444, 34.        ])

In [15]:
arr3-arr4

array([ 0.        , -0.44444444, -0.88888889, -1.33333333, -1.77777778,
       -2.22222222, -2.66666667, -3.11111111, -3.55555556, -4.        ])

**Q14**

In [16]:
str3='happy new year'
str3.split()

['happy', 'new', 'year']

**Q15**

In [17]:
str4='welcome'
str5='come'
if(str5 in str4):
    print('string present')
else:
    print('not present')

string present
